FROM python:3.12-alpine

RUN apk add --no-cache openssl

WORKDIR /app

RUN pip install pytest --no-cache-dir

COPY generate_certs.sh ./
COPY src/ src/
COPY tests/ tests/

CMD ["pytest", "-v", "tests/"]
