"""initial schema: pgvector extension, incidents, recommendations, feedback, suggestion_scores

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-06

Hand-written (not autogenerated) so the special bits can be reviewed without a
live DB and expressed exactly:

  1. ``CREATE EXTENSION IF NOT EXISTS vector`` FIRST — the ``vector`` column type
     and operator classes below depend on it existing.
  2. The four core tables with FKs and btree indexes. Column types mirror
     ``src/db/models.py`` exactly (timezone-aware DateTime, PostgreSQL JSONB /
     text[]; the ``incidents.embedding`` column is ``vector(384)`` and NULLable —
     embeddings are computed later, in C5).
  3. An **HNSW** index over ``incidents.embedding`` using ``vector_cosine_ops``
     (MiniLM output is L2-normalized → cosine distance) to power ANN retrieval.

``downgrade()`` drops the indexes and tables in reverse dependency order. The
``vector`` extension is intentionally left in place (dropping a shared extension
is riskier than the space it reclaims).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Embedding dimensionality (all-MiniLM-L6-v2 → 384); mirrors
# ``src.db.models.EMBEDDING_DIM``.
_EMBEDDING_DIM = 384


def upgrade() -> None:
    # --- pgvector extension (MUST precede the vector column / index) ------- #
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # --- incidents -------------------------------------------------------- #
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Populated in C5; NULLable in C2. HNSW cosine index added below.
        sa.Column("embedding", Vector(_EMBEDDING_DIM), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_incidents_service", "incidents", ["service"])
    op.create_index("ix_incidents_severity", "incidents", ["severity"])
    op.create_index("ix_incidents_created_at", "incidents", ["created_at"])

    # --- recommendations -------------------------------------------------- #
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("query_json", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendations_query_hash", "recommendations", ["query_hash"]
    )

    # --- feedback --------------------------------------------------------- #
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("query_pattern", sa.String(length=256), nullable=False),
        sa.Column("helpful", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"]),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feedback_recommendation_id", "feedback", ["recommendation_id"]
    )
    op.create_index("ix_feedback_incident_id", "feedback", ["incident_id"])
    op.create_index("ix_feedback_query_pattern", "feedback", ["query_pattern"])

    # --- suggestion_scores (learned aggregate, composite PK) -------------- #
    op.create_table(
        "suggestion_scores",
        sa.Column("query_pattern", sa.String(length=256), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column(
            "helpful_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "unhelpful_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"]),
        sa.PrimaryKeyConstraint("query_pattern", "incident_id"),
    )
    op.create_index(
        "ix_suggestion_scores_incident_id", "suggestion_scores", ["incident_id"]
    )

    # --- HNSW ANN index on the incident embedding (cosine) ---------------- #
    # Built after the table exists. ``IF NOT EXISTS`` keeps the migration
    # idempotent if partially re-applied. MiniLM vectors are L2-normalized, so
    # cosine distance (``vector_cosine_ops`` / the ``<=>`` operator) is correct.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_incidents_embedding_hnsw "
        "ON incidents USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # Drop the ANN index first, then tables in reverse dependency order.
    op.execute("DROP INDEX IF EXISTS ix_incidents_embedding_hnsw")

    op.drop_index(
        "ix_suggestion_scores_incident_id", table_name="suggestion_scores"
    )
    op.drop_table("suggestion_scores")

    op.drop_index("ix_feedback_query_pattern", table_name="feedback")
    op.drop_index("ix_feedback_incident_id", table_name="feedback")
    op.drop_index("ix_feedback_recommendation_id", table_name="feedback")
    op.drop_table("feedback")

    op.drop_index("ix_recommendations_query_hash", table_name="recommendations")
    op.drop_table("recommendations")

    op.drop_index("ix_incidents_created_at", table_name="incidents")
    op.drop_index("ix_incidents_severity", table_name="incidents")
    op.drop_index("ix_incidents_service", table_name="incidents")
    op.drop_table("incidents")

    # The `vector` extension is intentionally left in place on downgrade.
