"""initial schema: metrics, forecasts, model_metadata, accuracy_records

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-26

Creates the four core tables and their indexes. Hand-written (not autogenerated)
so it can be reviewed without a live DB; column types mirror ``src/db/models.py``
exactly (timezone-aware DateTime, PostgreSQL JSONB for JSON payloads).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- metrics ---------------------------------------------------------- #
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_metrics_metric_name", "metrics", ["metric_name"])
    op.create_index("ix_metrics_timestamp", "metrics", ["timestamp"])
    op.create_index(
        "ix_metrics_name_timestamp", "metrics", ["metric_name", "timestamp"]
    )

    # --- forecasts -------------------------------------------------------- #
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_minutes", sa.Integer(), nullable=False),
        sa.Column("horizon_steps", sa.Integer(), nullable=False),
        sa.Column("ensemble_prediction", postgresql.JSONB(), nullable=False),
        sa.Column("ensemble_confidence", postgresql.JSONB(), nullable=False),
        sa.Column("individual_forecasts", postgresql.JSONB(), nullable=False),
        sa.Column("step_timestamps", postgresql.JSONB(), nullable=False),
        sa.Column("alert_level", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_forecasts_metric_name", "forecasts", ["metric_name"])
    op.create_index("ix_forecasts_created_at", "forecasts", ["created_at"])
    op.create_index(
        "ix_forecasts_name_created_at", "forecasts", ["metric_name", "created_at"]
    )

    # --- model_metadata --------------------------------------------------- #
    op.create_table(
        "model_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_deployed", sa.Boolean(), nullable=False),
        sa.Column("params", postgresql.JSONB(), nullable=True),
        sa.Column("artifact_path", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_metadata_model_name",
        "model_metadata",
        ["model_name"],
        unique=True,
    )

    # --- accuracy_records ------------------------------------------------- #
    op.create_table(
        "accuracy_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_minutes", sa.Integer(), nullable=False),
        sa.Column("predicted_value", sa.Float(), nullable=False),
        sa.Column("actual_value", sa.Float(), nullable=True),
        sa.Column("absolute_error", sa.Float(), nullable=True),
        sa.Column("percentage_error", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_accuracy_records_model_name", "accuracy_records", ["model_name"]
    )
    op.create_index(
        "ix_accuracy_records_metric_name", "accuracy_records", ["metric_name"]
    )
    op.create_index(
        "ix_accuracy_records_evaluated_at", "accuracy_records", ["evaluated_at"]
    )
    op.create_index(
        "ix_accuracy_model_metric_evaluated",
        "accuracy_records",
        ["model_name", "metric_name", "evaluated_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_accuracy_model_metric_evaluated", table_name="accuracy_records")
    op.drop_index("ix_accuracy_records_evaluated_at", table_name="accuracy_records")
    op.drop_index("ix_accuracy_records_metric_name", table_name="accuracy_records")
    op.drop_index("ix_accuracy_records_model_name", table_name="accuracy_records")
    op.drop_table("accuracy_records")

    op.drop_index("ix_model_metadata_model_name", table_name="model_metadata")
    op.drop_table("model_metadata")

    op.drop_index("ix_forecasts_name_created_at", table_name="forecasts")
    op.drop_index("ix_forecasts_created_at", table_name="forecasts")
    op.drop_index("ix_forecasts_metric_name", table_name="forecasts")
    op.drop_table("forecasts")

    op.drop_index("ix_metrics_name_timestamp", table_name="metrics")
    op.drop_index("ix_metrics_timestamp", table_name="metrics")
    op.drop_index("ix_metrics_metric_name", table_name="metrics")
    op.drop_table("metrics")
