"""Tests for src.storage.sqlite_store.

Verifies that ``connect()`` applies every performance pragma from the
plan, that ``migrate()`` creates the ``logs`` table with the expected
columns and STORED generated columns, that the five indexes are
present, and that the generated columns produce the expected bucket
values on insert. Also verifies ``migrate()`` is idempotent.

All tests use the pytest ``tmp_path`` fixture so they run against a
fresh SQLite file and never touch the named app volume.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

from src.storage import sqlite_store


# ---------- helpers -------------------------------------------------


async def _open_and_migrate(tmp_path):
    """Shortcut: open + migrate a fresh DB under tmp_path."""
    db_file = str(tmp_path / "logs.db")
    conn = await sqlite_store.connect(db_file)
    await sqlite_store.migrate(conn)
    return conn


async def _pragma_value(conn, pragma: str):
    """Run ``PRAGMA <name>;`` and return the first column of the first row."""
    async with conn.execute(f"PRAGMA {pragma};") as cur:
        row = await cur.fetchone()
    if row is None:
        return None
    # aiosqlite.Row supports indexing by position.
    return row[0]


# ---------- pragmas -------------------------------------------------


async def test_pragmas_applied(tmp_path):
    """All pragmas from _PRAGMAS should be in effect after connect()."""
    db_file = str(tmp_path / "pragmas.db")
    conn = await sqlite_store.connect(db_file)
    try:
        journal_mode = await _pragma_value(conn, "journal_mode")
        synchronous = await _pragma_value(conn, "synchronous")
        cache_size = await _pragma_value(conn, "cache_size")
        mmap_size = await _pragma_value(conn, "mmap_size")
        temp_store = await _pragma_value(conn, "temp_store")

        # journal_mode is a string; WAL comes back lowercase from sqlite.
        assert str(journal_mode).lower() == "wal"
        # synchronous: 1 == NORMAL
        assert int(synchronous) == 1
        # cache_size: negative means KiB, -64000 == 64 MiB
        assert int(cache_size) == -64000
        # mmap_size: 256 MiB
        assert int(mmap_size) == 268435456
        # temp_store: 2 == MEMORY
        assert int(temp_store) == 2
    finally:
        await sqlite_store.close(conn)


# ---------- schema --------------------------------------------------


async def test_migrate_creates_table_and_columns(tmp_path):
    """logs table should exist with all expected columns including generated ones."""
    conn = await _open_and_migrate(tmp_path)
    try:
        # PRAGMA table_xinfo returns rows for ALL columns including
        # STORED generated columns (regular table_info hides them):
        # (cid, name, type, notnull, dflt_value, pk, hidden)
        async with conn.execute("PRAGMA table_xinfo('logs');") as cur:
            rows = await cur.fetchall()

        columns = {row[1]: {"type": row[2], "notnull": row[3], "pk": row[5]} for row in rows}

        expected = {
            "id": "TEXT",
            "ts": "INTEGER",
            "service": "TEXT",
            "level": "TEXT",
            "region": "TEXT",
            "response_time_ms": "REAL",
            "source_ip": "TEXT",
            "request_id": "TEXT",
            "message": "TEXT",
            "metadata": "TEXT",
            "latency_bucket": "TEXT",
            "hour_bucket": "INTEGER",
        }
        for col, typ in expected.items():
            assert col in columns, f"missing column {col!r} in logs table"
            assert columns[col]["type"].upper() == typ.upper(), (
                f"column {col!r} expected type {typ}, got {columns[col]['type']}"
            )

        # id is PK
        assert columns["id"]["pk"] == 1

        # Verify generated columns are actually declared GENERATED by
        # looking at the table DDL in sqlite_master.
        async with conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='logs';"
        ) as cur:
            row = await cur.fetchone()
        assert row is not None
        ddl = row[0]
        assert "GENERATED" in ddl.upper(), f"expected GENERATED columns in DDL, got: {ddl}"
        assert "latency_bucket" in ddl
        assert "hour_bucket" in ddl
    finally:
        await sqlite_store.close(conn)


# ---------- generated column computation ---------------------------


async def _insert_row(conn, *, row_id: str, ts: int, response_time_ms: float):
    """Insert a minimal logs row and commit; returns nothing."""
    await conn.execute(
        """
        INSERT INTO logs (id, ts, service, level, region, response_time_ms, message)
        VALUES (?, ?, ?, ?, ?, ?, ?);
        """,
        (row_id, ts, "payments", "INFO", "us-east-1", response_time_ms, "hello"),
    )
    await conn.commit()


async def _get_buckets(conn, row_id: str):
    async with conn.execute(
        "SELECT latency_bucket, hour_bucket FROM logs WHERE id=?;",
        (row_id,),
    ) as cur:
        row = await cur.fetchone()
    assert row is not None, f"row {row_id} not found"
    return row[0], row[1]


async def test_generated_columns_compute_on_insert(tmp_path):
    """latency_bucket and hour_bucket should compute correctly on every row."""
    conn = await _open_and_migrate(tmp_path)
    try:
        # 150ms in the "100-500ms" band; ts=1712000000 -> Apr 1 2024 20:53:20 UTC -> hour 20
        ts_mid = 1712000000
        await _insert_row(conn, row_id="mid", ts=ts_mid, response_time_ms=150.0)
        latency, hour = await _get_buckets(conn, "mid")
        assert latency == "100-500ms"
        # Compute expected hour the same way the DDL does: UTC hour via strftime %H.
        expected_hour = datetime.fromtimestamp(ts_mid, tz=timezone.utc).hour
        assert int(hour) == expected_hour

        # 50ms -> "0-100ms"
        await _insert_row(conn, row_id="low", ts=ts_mid, response_time_ms=50.0)
        latency, _ = await _get_buckets(conn, "low")
        assert latency == "0-100ms"

        # 2500ms -> "2s+"
        await _insert_row(conn, row_id="high", ts=ts_mid, response_time_ms=2500.0)
        latency, _ = await _get_buckets(conn, "high")
        assert latency == "2s+"

        # boundary: 500ms -> "500ms-2s" (CASE uses < 500 for "100-500ms")
        await _insert_row(conn, row_id="boundary_500", ts=ts_mid, response_time_ms=500.0)
        latency, _ = await _get_buckets(conn, "boundary_500")
        assert latency == "500ms-2s"
    finally:
        await sqlite_store.close(conn)


# ---------- indexes -------------------------------------------------


async def test_indexes_present(tmp_path):
    """All five expected indexes should be created by migrate()."""
    conn = await _open_and_migrate(tmp_path)
    try:
        async with conn.execute("PRAGMA index_list('logs');") as cur:
            rows = await cur.fetchall()

        # PRAGMA index_list rows: (seq, name, unique, origin, partial)
        names = {row[1] for row in rows}
        expected = {
            "idx_ts_service_level",
            "idx_region_ts",
            "idx_level_ts",
            "idx_latency_bucket",
            "idx_hour_bucket",
        }
        missing = expected - names
        assert not missing, f"missing indexes: {missing} (got {names})"
    finally:
        await sqlite_store.close(conn)


# ---------- idempotency --------------------------------------------


async def test_migrate_is_idempotent(tmp_path):
    """Calling migrate() twice should not raise nor alter row count."""
    db_file = str(tmp_path / "idem.db")
    conn = await sqlite_store.connect(db_file)
    try:
        await sqlite_store.migrate(conn)

        # Insert a row between migrations to confirm no data loss.
        await _insert_row(conn, row_id="only", ts=1712000000, response_time_ms=120.0)

        async with conn.execute("SELECT COUNT(*) FROM logs;") as cur:
            (before,) = await cur.fetchone()
        assert before == 1

        # Second migrate call should be a no-op.
        await sqlite_store.migrate(conn)

        async with conn.execute("SELECT COUNT(*) FROM logs;") as cur:
            (after,) = await cur.fetchone()
        assert after == before, "row count changed across migrate() calls"
    finally:
        await sqlite_store.close(conn)
