FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY tests/ tests/
COPY main.py server_main.py sample_logs.txt ./

CMD ["pytest", "-v", "--tb=short", "--cov=src"]
