"""Unit tests for src.collector.LogCollector — parsing, buffering, counters, and
the 1000-line burst gate that proves the hot path meets the throughput design.

Deterministic: seeded generators and simulated clocks throughout — the only wall
clock used is the perf_counter stopwatch inside the burst gate.
"""

import random
import time

from src.aggregation import MetricAggregator
from src.collector import LogCollector
from src.config import Settings
from src.generators import LogGenerator
from src.models import LogEvent, SourceType

EPOCH = 1000.0


def make_collector(buffer_size: int = 5000, seed: int = 42) -> LogCollector:
    """A store-less collector with pinned settings and a seeded generator."""
    settings = Settings(
        _env_file=None,  # hermetic: ignore any ambient .env
        events_per_second=120,
        event_buffer_size=buffer_size,
    )
    generator = LogGenerator(settings, rng=random.Random(seed))
    return LogCollector(settings, generator, MetricAggregator(), store=None)


def test_tick_parses_and_buffers_events():
    collector = make_collector()
    events = collector.tick(EPOCH)
    assert events, "tick 0 must emit at least the spawn/noise/scenario lines"
    assert all(isinstance(ev, LogEvent) for ev in events)
    assert len(collector.buffer) == len(events)
    assert collector.events_total == len(events)
    assert collector.parse_errors == 0


def test_buffer_is_bounded_by_settings():
    collector = make_collector(buffer_size=100)
    for i in range(30):
        collector.tick(EPOCH + i)
    assert collector.events_total > 100  # the deque really overflowed...
    assert len(collector.buffer) <= 100  # ...and maxlen kept it bounded


def test_garbage_lines_count_parse_errors_without_raising(monkeypatch):
    collector = make_collector()
    monkeypatch.setattr(
        collector.generator,
        "generate",
        lambda now: [(SourceType.WEB, ">> not an nginx line <<")],
    )
    events = collector.tick(EPOCH)
    assert events == []
    assert collector.parse_errors == 1
    assert collector.events_total == 0


def test_recent_returns_newest_first():
    collector = make_collector()
    for i in range(5):
        collector.tick(EPOCH + i)
    recent = collector.recent(5)
    assert len(recent) == 5
    assert recent[0].timestamp >= recent[4].timestamp
    assert recent[0] is collector.buffer[-1]  # index 0 IS the newest buffered event
    assert collector.recent(0) == []
    # Over-asking is clamped to whatever the buffer holds.
    assert len(collector.recent(10**6)) == len(collector.buffer)


def test_events_per_sec_ema_updates():
    collector = make_collector()
    for i in range(3):
        collector.tick(EPOCH + i)
    assert collector.events_per_sec > 0.0


def test_burst_of_1000_lines_processes_under_one_second(monkeypatch):
    """The C3 throughput gate: 1000 raw lines through one tick in < 1.0s.

    Raw lines are pre-generated by draining a separate seeded generator (so
    formatting cost is excluded), then fed to a single tick — timing exactly the
    parse + buffer + aggregate hot path the 1000 events/sec design relies on.
    """
    feeder = LogGenerator(
        Settings(_env_file=None, events_per_second=120), rng=random.Random(7)
    )
    lines: list[tuple[SourceType, str]] = []
    now = EPOCH
    while len(lines) < 1000:
        lines.extend(feeder.generate(now))
        now += 1.0
    lines = lines[:1000]

    collector = make_collector(seed=1)
    monkeypatch.setattr(collector.generator, "generate", lambda _now: lines)
    start = time.perf_counter()
    events = collector.tick(now)
    elapsed = time.perf_counter() - start

    assert len(events) == 1000
    assert collector.parse_errors == 0
    assert len(collector.buffer) == 1000
    assert elapsed < 1.0, f"1000-line burst took {elapsed:.3f}s (budget 1.0s)"
