"""Unit tests for ``src/persistence/models.py``.

These cover three layers:

  1. Schema metadata — table names, column presence, key indexes.
  2. Round-trip — insert + fetch each model through the in-memory
     ``session_factory`` fixture defined in ``tests/conftest.py``.
  3. Constraints — the audit chain's ``entry_hash`` UNIQUE rule
     actually surfaces ``IntegrityError`` on a duplicate insert.
"""
from __future__ import annotations

from datetime import datetime, timedelta

import pytest
import sqlalchemy as sa
from sqlalchemy.exc import IntegrityError

from src.persistence.models import (
    AuditEntry,
    Base,
    File,
    JobRun,
    PendingDelete,
    Transition,
)


# --- Static schema checks ----------------------------------------------------


def test_all_models_exported():
    """The five ORM classes plus Base must be importable from the module."""
    # Smoke check — if the import at the top failed, the test wouldn't even
    # collect; this just makes the contract explicit.
    assert Base is not None
    for cls in (File, Transition, PendingDelete, AuditEntry, JobRun):
        assert cls.__tablename__ in {
            "files",
            "transitions",
            "pending_deletes",
            "audit_entries",
            "job_runs",
        }


def test_file_columns():
    cols = set(File.__table__.columns.keys())
    expected = {
        "id",
        "source",
        "category",
        "segment_path",
        "tier",
        "size_bytes",
        "oldest_record_ts",
        "newest_record_ts",
        "compliance_tag",
        "immutable",
        "next_eval_at",
        "created_at",
    }
    assert cols == expected, f"missing={expected - cols} extra={cols - expected}"
    assert File.__table__.columns["segment_path"].unique is True
    # ``category`` is a nullable indexed string; the scanner reads it to
    # match policies, so a missing column would silently break the demo.
    assert File.__table__.columns["category"].nullable is True


def test_audit_entry_seq_no_autoincrement():
    """``seq`` is the PK but autoincrement is OFF — appender sets it."""
    col = AuditEntry.__table__.columns["seq"]
    assert col.primary_key is True
    assert col.autoincrement is False


def test_audit_entry_entry_hash_unique():
    col = AuditEntry.__table__.columns["entry_hash"]
    assert col.unique is True


# --- Indexes -----------------------------------------------------------------


@pytest.mark.asyncio
async def test_indexes_exist(engine):
    """All required indexes are created on the live SQLite schema."""
    async with engine.connect() as conn:
        result = await conn.exec_driver_sql(
            "SELECT name, tbl_name FROM sqlite_master WHERE type='index';"
        )
        rows = result.fetchall()
    # We can't pin index names for SQLAlchemy-autogenerated ones (they look
    # like ix_files_tier), so we check tbl_name + the columns covered.
    index_by_name = {name: tbl for name, tbl in rows}
    # SQLAlchemy auto-generates names of the form ix_<table>_<column>.
    assert "ix_files_tier" in index_by_name
    assert "ix_files_next_eval_at" in index_by_name
    assert "ix_files_source" in index_by_name
    assert "ix_files_category" in index_by_name
    assert "ix_transitions_status" in index_by_name
    assert "ix_transitions_file_id" in index_by_name
    assert "ix_pending_deletes_delete_after" in index_by_name
    assert "ix_audit_entries_actor_ts" in index_by_name  # composite
    assert "ix_job_runs_job_name" in index_by_name


@pytest.mark.asyncio
async def test_audit_entries_composite_index_columns(engine):
    """The composite index is on (actor, ts_utc) in that order."""
    async with engine.connect() as conn:
        result = await conn.exec_driver_sql(
            "PRAGMA index_info('ix_audit_entries_actor_ts');"
        )
        rows = result.fetchall()
    # PRAGMA index_info returns (seqno, cid, name) — sort by seqno.
    col_names = [row[2] for row in sorted(rows, key=lambda r: r[0])]
    assert col_names == ["actor", "ts_utc"]


# --- Round-trip tests --------------------------------------------------------


@pytest.mark.asyncio
async def test_file_round_trip(session_factory):
    """Insert a ``File`` row; fetch it back; every field matches."""
    oldest = datetime(2026, 1, 1, 0, 0, 0)
    newest = datetime(2026, 1, 1, 12, 0, 0)
    next_eval = datetime(2026, 1, 2, 0, 0, 0)
    async with session_factory() as session:
        f = File(
            source="app-1",
            category="payment",
            segment_path="/tiers/hot/segment-1.jsonl",
            tier="hot",
            size_bytes=2048,
            oldest_record_ts=oldest,
            newest_record_ts=newest,
            compliance_tag="sox",
            immutable=False,
            next_eval_at=next_eval,
        )
        session.add(f)
        await session.commit()
        file_id = f.id

    async with session_factory() as session:
        result = await session.execute(sa.select(File).where(File.id == file_id))
        fetched = result.scalar_one()
    assert fetched.id == file_id
    assert fetched.source == "app-1"
    assert fetched.category == "payment"
    assert fetched.segment_path == "/tiers/hot/segment-1.jsonl"
    assert fetched.tier == "hot"
    assert fetched.size_bytes == 2048
    assert fetched.oldest_record_ts == oldest
    assert fetched.newest_record_ts == newest
    assert fetched.compliance_tag == "sox"
    assert fetched.immutable is False
    assert fetched.next_eval_at == next_eval
    assert fetched.created_at is not None


@pytest.mark.asyncio
async def test_transition_foreign_key(session_factory):
    """Inserting a Transition that references a real File round-trips both."""
    async with session_factory() as session:
        f = File(
            source="app-2",
            segment_path="/tiers/hot/segment-2.jsonl",
            tier="hot",
            size_bytes=1024,
            oldest_record_ts=datetime(2026, 1, 1),
            newest_record_ts=datetime(2026, 1, 1),
        )
        session.add(f)
        await session.flush()  # get f.id without committing
        t = Transition(
            file_id=f.id,
            from_tier="hot",
            to_tier="warm",
            action="promote",
            status="pending",
        )
        session.add(t)
        await session.commit()
        file_id, transition_id = f.id, t.id

    async with session_factory() as session:
        file_row = (
            await session.execute(sa.select(File).where(File.id == file_id))
        ).scalar_one()
        tx_row = (
            await session.execute(
                sa.select(Transition).where(Transition.id == transition_id)
            )
        ).scalar_one()
    assert tx_row.file_id == file_row.id
    assert tx_row.from_tier == "hot"
    assert tx_row.to_tier == "warm"
    assert tx_row.action == "promote"
    assert tx_row.status == "pending"
    assert tx_row.error is None
    assert tx_row.executed_at is None
    assert tx_row.planned_at is not None


@pytest.mark.asyncio
async def test_pending_delete_round_trip(session_factory):
    """Inserting a ``PendingDelete`` and reading it back keeps every field."""
    delete_after = datetime(2026, 6, 1, 0, 0, 0)
    async with session_factory() as session:
        f = File(
            source="app-3",
            segment_path="/tiers/pending/segment-3.jsonl",
            tier="pending",
            size_bytes=512,
            oldest_record_ts=datetime(2026, 1, 1),
            newest_record_ts=datetime(2026, 1, 1),
        )
        session.add(f)
        await session.flush()
        pd = PendingDelete(
            file_id=f.id,
            path="/tiers/pending/segment-3.jsonl",
            delete_after=delete_after,
        )
        session.add(pd)
        await session.commit()
        pd_id = pd.id

    async with session_factory() as session:
        fetched = (
            await session.execute(sa.select(PendingDelete).where(PendingDelete.id == pd_id))
        ).scalar_one()
    assert fetched.path == "/tiers/pending/segment-3.jsonl"
    assert fetched.delete_after == delete_after
    assert fetched.created_at is not None


@pytest.mark.asyncio
async def test_audit_entry_unique_entry_hash(session_factory):
    """Two ``AuditEntry`` rows with the same ``entry_hash`` raise IntegrityError."""
    common_hash = "a" * 64
    async with session_factory() as session:
        e1 = AuditEntry(
            seq=1,
            ts_utc=datetime(2026, 1, 1, 0, 0, 0),
            actor="system",
            action="test",
            resource="r1",
            metadata_json="{}",
            prev_hash="0" * 64,
            entry_hash=common_hash,
        )
        session.add(e1)
        await session.commit()

    with pytest.raises(IntegrityError):
        async with session_factory() as session:
            e2 = AuditEntry(
                seq=2,
                ts_utc=datetime(2026, 1, 1, 0, 0, 1),
                actor="system",
                action="test",
                resource="r2",
                metadata_json="{}",
                prev_hash=common_hash,  # would normally chain off e1
                entry_hash=common_hash,  # duplicate — must fail
            )
            session.add(e2)
            await session.commit()


@pytest.mark.asyncio
async def test_audit_entry_round_trip(session_factory):
    """Round-trip a full audit entry to make sure the column shapes hold."""
    ts = datetime(2026, 1, 1, 0, 0, 0)
    async with session_factory() as session:
        e = AuditEntry(
            seq=42,
            ts_utc=ts,
            actor="lifecycle.applier",
            action="transition_applied",
            resource="file:123",
            metadata_json='{"from":"hot","to":"warm"}',
            prev_hash="0" * 64,
            entry_hash="b" * 64,
        )
        session.add(e)
        await session.commit()

    async with session_factory() as session:
        fetched = (
            await session.execute(sa.select(AuditEntry).where(AuditEntry.seq == 42))
        ).scalar_one()
    assert fetched.actor == "lifecycle.applier"
    assert fetched.action == "transition_applied"
    assert fetched.resource == "file:123"
    assert fetched.metadata_json == '{"from":"hot","to":"warm"}'
    assert fetched.prev_hash == "0" * 64
    assert fetched.entry_hash == "b" * 64
    assert fetched.ts_utc == ts


@pytest.mark.asyncio
async def test_job_run_round_trip(session_factory):
    """``JobRun`` round-trips; ``finished_at`` and ``summary_json`` are nullable."""
    started = datetime(2026, 1, 1, 0, 0, 0)
    finished = started + timedelta(seconds=2)
    async with session_factory() as session:
        # Pending run (no finish yet).
        r1 = JobRun(job_name="scan", started_at=started, status="running")
        session.add(r1)
        await session.commit()
        r1_id = r1.id

        # Completed run.
        r2 = JobRun(
            job_name="apply",
            started_at=started,
            finished_at=finished,
            status="ok",
            summary_json='{"applied":3}',
        )
        session.add(r2)
        await session.commit()
        r2_id = r2.id

    async with session_factory() as session:
        running = (
            await session.execute(sa.select(JobRun).where(JobRun.id == r1_id))
        ).scalar_one()
        done = (
            await session.execute(sa.select(JobRun).where(JobRun.id == r2_id))
        ).scalar_one()
    assert running.job_name == "scan"
    assert running.finished_at is None
    assert running.summary_json is None
    assert running.status == "running"
    assert done.finished_at == finished
    assert done.summary_json == '{"applied":3}'
    assert done.status == "ok"
