FROM python:3.12-alpine
RUN pip install --no-cache-dir pyyaml==6.0.2 flask==3.1.0
WORKDIR /app
COPY shared/ shared/
COPY query/ query/
COPY config.yml config.yml
CMD ["python", "-m", "query.web_main"]
