"""Alembic environment for the Log Recommendation Engine.

The database URL is read from ``src.config.get_settings().database_url`` (never
hardcoded). ``src.db.models`` is imported so every table is registered on
``Base.metadata``, which becomes Alembic's ``target_metadata`` (enabling
autogenerate and offline DDL). Both offline and online modes are supported.

``compare_type=True`` lets autogenerate notice column-type changes on later
revisions; the special bits (the ``vector`` extension and the HNSW index) are
hand-written in the initial migration rather than autogenerated.
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Ensure the project root (which contains the `src` package) is importable when
# Alembic runs from the `migrations/` working dir or from /app in the container.
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from src.config import get_settings  # noqa: E402
from src.db.base import Base  # noqa: E402
import src.db.models  # noqa: E402,F401  (import for side effect: registers tables)

# Alembic Config object; provides access to .ini values.
config = context.config

# Inject the application's DB URL so the .ini placeholder is never used.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

# Configure Python logging from the .ini if present.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Target metadata for autogenerate support.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL, no live DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply against the DB)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
